version: "3.5"
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=database
        ports:
            - "8888:80"
            
    database:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=db_pessoas
            - MYSQL_ROOT_PASSWORD=welcome1
        volumes:
            - ./database/startup:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"